#!/bin/python3
import re
from sympy import sympify, simplify
from sympy.parsing.latex import parse_latex
from inginious import input, feedback, rst

somme = 10000*int(input.get_input("@random")[0] * 100 + 1)
plus2 = 1000*int(input.get_input("@random")[1] * 100 + 1)
minus3 = 1000*int(input.get_input("@random")[2] * 100 + 1)

correct_equation = str(somme) + " = x + x + " + str(plus2) + " + x  + " + str(plus2)  + " - " + str(minus3)

def parse_equation(latex_str):
    # The \left and \right prefix are not supported by sympy (and useless for treatment)
    latex_str = re.sub("(\\\left|\\\\right)", "", latex_str)
    return parse_latex(latex_str)

def is_equal(eq1, eq2):
    return simplify(eq1) == simplify(eq2) or simplify(sympify(str(eq1))) == simplify(sympify(str(eq2)))

try:
    student_answer = parse_equation(input.get_input("math1"))
    correct_answer = parse_equation(correct_equation)
except LaTeXParsingError as e:
    feedback.set_global_result("failed")
    feedback.set_global_feedback("parsing error")

if is_equal(student_answer, correct_answer):
    feedback.set_global_result("success")
else:
    feedback.set_global_result("failed")
    feedback.set_global_feedback("wrong answer")